// Mock Database - Edit this file to manually update products and bills
// This structure is ready for easy migration to Supabase

import { Product, Bill } from './types';

export const initialProducts: Product[] = [
    {
        id: '1',
        name: 'Cursor Vô Hạn Request',
        icon: 'Code',
        description: 'Sử dụng được model Claude 4.5 Sonnet, Gpt 5.1, Gpt 5.2, Gemini 3 Pro, auto',
        features: [
            'Claude 4.5 Sonnet',
            'GPT 5.1 & GPT 5.2',
            'Gemini 3 Pro',
            'Auto mode',
        ],
        pricingTiers: [
            { duration: '1 ngày', requestLimit: 'Vô Hạn', price: 25000 },
            { duration: '7 ngày', requestLimit: 'Vô Hạn', price: 90000, isPopular: true },
            { duration: '1 tháng', requestLimit: 'Vô Hạn', price: 250000 },
            { duration: '3 tháng', requestLimit: 'Vô Hạn', price: 500000 },
            { duration: '1 năm', requestLimit: 'Vô Hạn', price: 1300000 },
        ],
        tag: 'Best Seller',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '2',
        name: 'Cursor Pro Plan 20$',
        icon: 'Code',
        description: 'Đăng nhập qua tài khoản mật khẩu hỗ trợ full model. Sử dụng tối đa 70$.',
        features: [
            'Đăng nhập tài khoản/mật khẩu',
            'Hỗ trợ full model',
            'Sử dụng tối đa 70$',
        ],
        pricingTiers: [
            { duration: '1 tháng', requestLimit: 'Hết 70$ là hết', price: 280000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '3',
        name: 'Augment Vô Hạn Request',
        icon: 'Sparkles',
        description: 'Sử dụng được model Claude 4.5 Sonnet, Claude 4.5 Haiku, Gpt 5.1, Gpt 5.2, Gemini 3 Pro',
        features: [
            'Claude 4.5 Sonnet & Haiku',
            'GPT 5.1 & GPT 5.2',
            'Gemini 3 Pro',
        ],
        pricingTiers: [
            { duration: '1 ngày', requestLimit: 'Vô Hạn', price: 25000 },
            { duration: '7 ngày', requestLimit: 'Vô Hạn', price: 90000, isPopular: true },
            { duration: '2 tuần', requestLimit: 'Vô Hạn', price: 140000 },
            { duration: '1 tháng', requestLimit: 'Vô Hạn', price: 230000 },
        ],
        tag: 'Hot',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '4',
        name: 'Augment - Credit',
        icon: 'Sparkles',
        description: 'Hỗ trợ full model với hệ thống credit',
        features: [
            'Hỗ trợ full model',
            'Tính theo credit',
        ],
        pricingTiers: [
            { duration: '3 ngày', requestLimit: '5$', price: 40000 },
            { duration: '7 ngày', requestLimit: '10$', price: 80000, isPopular: true },
            { duration: '14 ngày', requestLimit: '21$', price: 160000 },
            { duration: '1 tháng', requestLimit: '52$', price: 350000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '5',
        name: 'Windsurf',
        icon: 'Code',
        description: 'Hỗ trợ nick freeplan only',
        features: [
            'Hỗ trợ nick freeplan',
            'Unlimited request',
        ],
        pricingTiers: [
            { duration: '1 ngày', requestLimit: 'Vô Hạn', price: 20000 },
            { duration: '7 ngày', requestLimit: 'Vô Hạn', price: 40000, isPopular: true },
            { duration: '2 tuần', requestLimit: 'Vô Hạn', price: 80000 },
            { duration: '1 tháng', requestLimit: 'Vô Hạn', price: 100000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '6',
        name: 'KiroCode',
        icon: 'Code',
        description: 'Hỗ trợ full model',
        features: [
            'Hỗ trợ full model',
            'Request theo gói',
        ],
        pricingTiers: [
            { duration: '3 ngày', requestLimit: '1500 Request', price: 30000 },
            { duration: '7 ngày', requestLimit: '2500 Request', price: 50000, isPopular: true },
            { duration: '2 tuần', requestLimit: '5000 Request', price: 70000 },
            { duration: '1 tháng', requestLimit: '10000 Request', price: 120000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '7',
        name: 'GitHub Copilot Pro Plan',
        icon: 'Github',
        description: 'Đăng nhập qua tài khoản mật khẩu hỗ trợ full model',
        features: [
            'Đăng nhập tài khoản/mật khẩu',
            'Hỗ trợ full model',
            '300 Request/tháng',
        ],
        pricingTiers: [
            { duration: '1 tháng', requestLimit: '300 Request', price: 100000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '8',
        name: 'Tài Khoản ChatGPT Plus',
        icon: 'MessageSquare',
        description: 'Bảo hành full tháng',
        features: [
            'Bảo hành full',
            'ChatGPT Plus đầy đủ tính năng',
        ],
        pricingTiers: [
            { duration: '1 tháng', requestLimit: 'Full access', price: 50000 },
        ],
        tag: 'Hot',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '9',
        name: 'Codex - CLI',
        icon: 'FileText',
        description: 'Hỗ trợ full model với 90$/ngày',
        features: [
            'Hỗ trợ full model',
            '90$/ngày',
        ],
        pricingTiers: [
            { duration: '1 ngày', requestLimit: '90$/ngày', price: 35000 },
            { duration: '7 ngày', requestLimit: '90$/ngày', price: 120000, isPopular: true },
            { duration: '14 ngày', requestLimit: '90$/ngày', price: 180000 },
            { duration: '1 tháng', requestLimit: '90$/ngày', price: 250000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '10',
        name: 'ClaudeCode - CLI',
        icon: 'Brain',
        description: 'Hỗ trợ full model',
        features: [
            'Hỗ trợ full model',
            'Claude CLI',
        ],
        pricingTiers: [
            { duration: '1 ngày', requestLimit: '10$', price: 45000 },
            { duration: '7 ngày', requestLimit: '20$ mỗi 5h', price: 450000, isPopular: true },
            { duration: '1 tháng', requestLimit: '20$ mỗi 5h', price: 1500000 },
        ],
        tag: 'New',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '11',
        name: 'Antigravity + Gemini Pro + 2TB Mail',
        icon: 'Sparkles',
        description: 'Hỗ trợ full model - Mail chính chủ',
        features: [
            'Antigravity',
            'Gemini Pro',
            '2TB Google Drive',
            'Mail chính chủ',
        ],
        pricingTiers: [
            { duration: '1 năm', requestLimit: 'Gói Developer', price: 100000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '12',
        name: 'Krea.ai',
        icon: 'Image',
        description: 'Bảo hành full tháng',
        features: [
            'Bảo hành full',
            'AI Image Generation',
        ],
        pricingTiers: [
            { duration: '1 tháng', requestLimit: 'Full access', price: 200000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '13',
        name: 'Vmake.ai',
        icon: 'Image',
        description: 'Bảo hành full tháng',
        features: [
            'Bảo hành full',
            'AI Video Generation',
        ],
        pricingTiers: [
            { duration: '1 tháng', requestLimit: 'Full access', price: 200000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '14',
        name: 'Higgsfield.ai',
        icon: 'Image',
        description: 'Nâng chính chủ + Cấp Acc',
        features: [
            'Nâng chính chủ',
            'Cấp Account',
        ],
        pricingTiers: [
            { duration: 'Basic - 1 tháng', requestLimit: 'Basic Plan', price: 150000 },
            { duration: 'Pro - 1 tháng', requestLimit: 'Pro Plan', price: 400000, isPopular: true },
            { duration: 'Ultimate - 1 tháng', requestLimit: 'Ultimate Plan', price: 700000 },
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
];

export const initialBills: Bill[] = [
    {
        id: '1',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+1',
        date: '2024-01-10',
        description: 'Giao dịch Cursor Pro',
        createdAt: '2024-01-10',
    },
    {
        id: '2',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+2',
        date: '2024-01-09',
        description: 'Giao dịch Augment',
        createdAt: '2024-01-09',
    },
    {
        id: '3',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+3',
        date: '2024-01-08',
        description: 'Giao dịch GitHub Copilot',
        createdAt: '2024-01-08',
    },
    {
        id: '4',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+4',
        date: '2024-01-07',
        description: 'Giao dịch ChatGPT Plus',
        createdAt: '2024-01-07',
    },
    {
        id: '5',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+5',
        date: '2024-01-06',
        createdAt: '2024-01-06',
    },
    {
        id: '6',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+6',
        date: '2024-01-05',
        createdAt: '2024-01-05',
    },
];
