// Mock Database - Edit this file to manually update products and bills
// This structure is ready for easy migration to Supabase

import { Product, Bill } from './types';

export const initialProducts: Product[] = [
    {
        id: '1',
        name: 'ChatGPT Plus',
        icon: 'MessageSquare',
        price: 350000,
        originalPrice: 500000,
        description: 'Truy cập GPT-4, DALL-E 3 và nhiều tính năng cao cấp khác.',
        features: [
            'GPT-4 & GPT-4o không giới hạn',
            'DALL-E 3 tạo ảnh AI',
            'Truy cập plugin & GPTs',
            'Ưu tiên khi cao tải',
        ],
        tag: 'Best Seller',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '2',
        name: 'Cursor Pro',
        icon: 'Code',
        price: 300000,
        originalPrice: 450000,
        description: 'IDE thông minh với AI hỗ trợ code mạnh mẽ nhất hiện nay.',
        features: [
            'Claude 3.5 Sonnet tích hợp',
            'Autocomplete thông minh',
            'Chat với codebase',
            'Refactor tự động',
        ],
        tag: 'Hot',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '3',
        name: 'GitHub Copilot',
        icon: 'Github',
        price: 280000,
        originalPrice: 400000,
        description: 'AI pair programmer giúp bạn code nhanh gấp 10 lần.',
        features: [
            'Gợi ý code real-time',
            'Hỗ trợ mọi ngôn ngữ',
            'Tích hợp VS Code',
            'Chat với Copilot',
        ],
        contactLink: 'https://m.me/pagename',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '4',
        name: 'Claude Pro',
        icon: 'Brain',
        price: 380000,
        originalPrice: 520000,
        description: 'AI thông minh nhất của Anthropic với context 200K tokens.',
        features: [
            'Claude 3.5 Sonnet',
            'Context window 200K',
            'Phân tích file & code',
            'Không giới hạn tin nhắn',
        ],
        tag: 'New',
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '5',
        name: 'Midjourney',
        icon: 'Image',
        price: 320000,
        originalPrice: 480000,
        description: 'Tạo ảnh AI chất lượng cao nhất thế giới.',
        features: [
            'Tạo ảnh không giới hạn',
            'Chất lượng 4K',
            'Style đa dạng',
            'Fast mode 24/7',
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
    {
        id: '6',
        name: 'Notion AI',
        icon: 'FileText',
        price: 200000,
        originalPrice: 300000,
        description: 'AI viết và tổ chức nội dung trong Notion.',
        features: [
            'Viết blog tự động',
            'Tóm tắt tài liệu',
            'Dịch đa ngôn ngữ',
            'Brainstorm ý tưởng',
        ],
        contactLink: 'https://zalo.me/0944568913',
        isActive: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01',
    },
];

export const initialBills: Bill[] = [
    {
        id: '1',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+1',
        date: '2024-01-10',
        description: 'Giao dịch ChatGPT Plus',
        createdAt: '2024-01-10',
    },
    {
        id: '2',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+2',
        date: '2024-01-09',
        description: 'Giao dịch Cursor Pro',
        createdAt: '2024-01-09',
    },
    {
        id: '3',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+3',
        date: '2024-01-08',
        description: 'Giao dịch GitHub Copilot',
        createdAt: '2024-01-08',
    },
    {
        id: '4',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+4',
        date: '2024-01-07',
        description: 'Giao dịch Claude Pro',
        createdAt: '2024-01-07',
    },
    {
        id: '5',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+5',
        date: '2024-01-06',
        createdAt: '2024-01-06',
    },
    {
        id: '6',
        imageUrl: 'https://placehold.co/400x600/1a1a2e/00ff88?text=Bill+6',
        date: '2024-01-05',
        createdAt: '2024-01-05',
    },
];
